name: Test, Build, and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t iamdivye/express-js:${{ github.run_number }} .
        docker tag iamdivye/express-js:${{ github.run_number }} iamdivye/express:latest

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push iamdivye/express:${{ github.run_number }}
