name: Node.js CI/CD

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the Node.js version you require
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # Replace with the actual build command for your application

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ubuntu@ >> ubuntu@3.90.183.196: ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ubuntu@3.90.183.196 "echo SSH is properly configured"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PASS }}

      - name: Copy app to EC2
        run: |
          rsync -av --exclude='node_modules' --exclude='test' --exclude='.*' ./ ubuntu@3.90.183.196:/home/ubuntu
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PASS }}

      - name: SSH into EC2 and deploy
        run: |
          ssh ubuntu@3.90.183.196 "cd /home && npm install && npm start"
