name: Node.js CI with SSH Deploy

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Updated to use Node.js 16
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm run test

 
     - name: Deploy to EC2  
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KEY }}
            HOSTNAME: ${{ secrets.AWS_IP }}
            USER_NAME: ${{ secrets.AWS_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
          script: |
            pm2 delete all
            git clone https://github.com/offender6969/expressjs-app /express
            cd /home/ubuntu/express
            git pull
            npm install
            pm2 start npm -- start
