name: Node.js CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    - name: Add SSH Key to Agent
      run: ssh-add <(echo "${{ secrets.AWS_KEY }}")

   name: Node.js CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    - name: Add SSH Key to Agent
      run: ssh-add <(echo "${{ secrets.AWS_KEY }}")

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{secrets.AWS_KEY}}
        host: ${{secrets.AWS_IP}}
        username: ${{secrets.AWS_UNAME}}
        script: |
          pm2 delete all
          git clone https://github.com/offender6969/expressjs-app /express
          cd /home/ubuntu/express
          git pull
          npm install
          pm2 start npm -- start

