name: Node.js CI with SSH Deploy

on:
  push: { branches: [master] }

jobs:

  
build:

    
runs-on:
 
ubuntu-latest


    
steps:

      
-
 
uses:
 
actions/checkout@v2

      
-
 
uses:
 
actions/setup-node@v2

        
with:

          
node-version:
 
16.x

      
-
 
run:
 
npm
 
install

      
-
 
run:
 
npm run build
      - run: npm run test
      - env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          HOSTNAME: ${{ secrets.AWS_IP }}
          USER_NAME: ${{ secrets.AWS_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/express
            git pull
            npm install
            pm2 start npm -- start
          '
